# Generated by Django 5.2.3 on 2025-06-14 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_fitnessclass_available_slots'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fitnessclass',
            old_name='name',
            new_name='class_name',
        ),
    ]
